package com.example.data.repository

import com.example.data.dao.DayTaskDao
import com.example.data.model.DayTask
import com.example.data.model.TaskMode
import kotlinx.coroutines.flow.Flow

class TaskRepository(private val dayTaskDao: DayTaskDao) {
    val allTasks: Flow<List<DayTask>> = dayTaskDao.getAllTasks()

    fun getTasksForDate(date: String): Flow<List<DayTask>> =
        dayTaskDao.getTasksForDate(date)

    suspend fun getTasksForDateList(date: String): List<DayTask> =
        dayTaskDao.getTasksForDateList(date)

    suspend fun getAllUndiscardedTasksList(): List<DayTask> =
        dayTaskDao.getAllUndiscardedTasksList()

    fun getTasksForDateAndMode(date: String, mode: TaskMode): Flow<List<DayTask>> =
        dayTaskDao.getTasksForDateAndMode(date, mode)

    fun getTasksByMode(mode: TaskMode): Flow<List<DayTask>> =
        dayTaskDao.getTasksByMode(mode)

    suspend fun getTaskById(id: Long): DayTask? = dayTaskDao.getTaskById(id)

    suspend fun insertTask(task: DayTask): Long = dayTaskDao.insertTask(task)

    suspend fun insertTasks(tasks: List<DayTask>): List<Long> = dayTaskDao.insertTasks(tasks)

    suspend fun updateTask(task: DayTask) = dayTaskDao.updateTask(task)

    suspend fun deleteTask(task: DayTask) = dayTaskDao.deleteTask(task)

    suspend fun deleteTaskById(id: Long) = dayTaskDao.deleteTaskById(id)

    suspend fun setTaskCompleted(id: Long, completed: Boolean) =
        dayTaskDao.setTaskCompleted(id, completed)

    suspend fun markTaskPassedAndDiscarded(id: Long) =
        dayTaskDao.markTaskPassedAndDiscarded(id)

    suspend fun voidTaskDueToExam(id: Long, reason: String) =
        dayTaskDao.voidTaskDueToExam(id, reason)

    suspend fun deleteAutoGeneratedTasksForDate(date: String) =
        dayTaskDao.deleteAutoGeneratedTasksForDate(date)

    suspend fun clearAllTasks() = dayTaskDao.clearAllTasks()
}
