package com.example.data.dao

import androidx.room.Dao
import androidx.room.Delete
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Update
import com.example.data.model.DayTask
import com.example.data.model.TaskMode
import kotlinx.coroutines.flow.Flow

@Dao
interface DayTaskDao {
    @Query("SELECT * FROM day_tasks ORDER BY isCompleted ASC, date ASC, time ASC")
    fun getAllTasks(): Flow<List<DayTask>>

    @Query("SELECT * FROM day_tasks WHERE date = :date ORDER BY isCompleted ASC, time ASC")
    fun getTasksForDate(date: String): Flow<List<DayTask>>

    @Query("SELECT * FROM day_tasks WHERE date = :date AND mode = :mode ORDER BY isCompleted ASC, time ASC")
    fun getTasksForDateAndMode(date: String, mode: TaskMode): Flow<List<DayTask>>

    @Query("SELECT * FROM day_tasks WHERE mode = :mode ORDER BY isCompleted ASC, date ASC, time ASC")
    fun getTasksByMode(mode: TaskMode): Flow<List<DayTask>>

    @Query("SELECT * FROM day_tasks WHERE id = :id LIMIT 1")
    suspend fun getTaskById(id: Long): DayTask?

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertTask(task: DayTask): Long

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertTasks(tasks: List<DayTask>): List<Long>

    @Update
    suspend fun updateTask(task: DayTask)

    @Delete
    suspend fun deleteTask(task: DayTask)

    @Query("DELETE FROM day_tasks WHERE id = :id")
    suspend fun deleteTaskById(id: Long)

    @Query("UPDATE day_tasks SET isCompleted = :completed WHERE id = :id")
    suspend fun setTaskCompleted(id: Long, completed: Boolean)

    @Query("DELETE FROM day_tasks WHERE date = :date AND linkedClassId IS NOT NULL")
    suspend fun deleteAutoGeneratedTasksForDate(date: String)
}
